//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2_sergio_individueel_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string Naam { get; set; }
        public decimal Inkoopprijs { get; set; }
        public decimal Marge { get; set; }
        public int Eenheid { get; set; }
        public Nullable<decimal> BTW { get; set; }
        public Nullable<int> LeverancierID { get; set; }
        public Nullable<int> CategorieID { get; set; }
    
        public virtual Categorie Categorie { get; set; }
        public virtual Leverancier Leverancier { get; set; }
    }
}
